#!/usr/bin/env node
'use strict';

const fs = require('fs');

const MESSAGE_PATH_CHAT = '/open-apis/im/v1/messages?receive_id_type=chat_id';
const MESSAGE_PATH_OPEN = '/open-apis/im/v1/messages?receive_id_type=open_id';
const APPROVAL_PATH = '/open-apis/approval/v4/instances?user_id_type=user_id';
const REVIEWER_OPEN_ID = 'ou_3d9067006e9fb8eb8e5fc7b2bb4c6264';
const REVIEW_FORM_BASE_URL = 'https://n8n.aelf.dev/form/reimbursement-review?submission_id=';
const APPROVAL_CODE = '599F145B-9E25-4746-A2DA-7B87DB92AD0F';
const AI_DISCLAIMER = 'This approval was auto-generated by AI reimbursement recognition system. Data was reviewed and confirmed by Finance before submission.';

const CATEGORY_MAP = {
  '技术服务费': 'lwkkktxl-xsh7nzjrjb-9',
  '员工福利': 'lwkkktxl-hsb5k4bhad5-5',
  '差旅费': 'lwkkktx1-a5eycrbdol7-0',
  '办公费': 'lwkkktx1-1lgmf4xvjn2-0',
  Others: 'mjch1lsy-kmowo0xjgxc-3'
};

const CURRENCY_MAP = {
  CNY: 'lwpzlrza-zoo84ker6o-0',
  SGD: 'lwpzlrza-w81tf7okwq-0',
  USDT: 'lwpzlrza-ppsossh61bd-0'
};

const WIDGETS = {
  field_list: 'widget17661255766760001',
  related_approval: 'widget17165489347490001',
  remarks: 'widget17667289445210001',
  row_department: 'widget17675914385750001',
  row_dept_head: 'widget17165475059790001',
  row_date: 'widget17661256619280001',
  row_category: 'widget17165483685010001',
  row_short_description: 'widget17661266428940001',
  row_description: 'widget17661277169490001',
  row_currency: 'widget17168759377620001',
  row_amount: 'widget17661271904410001',
  row_payee_name: 'widget17661238520260001',
  row_bank_name: 'widget17661239274280001',
  row_bank_account: 'widget17661240576810001',
  row_attachment: 'widget17165484992290001'
};

function readInput() {
  const text = fs.readFileSync(0, 'utf8');
  return text.trim() ? JSON.parse(text) : {};
}

function source(input) {
  return input && input.body && typeof input.body === 'object' ? input.body : input;
}

function firstValue(record, names) {
  for (const name of names) {
    const value = record ? record[name] : undefined;
    if (value !== undefined && value !== null && String(value).trim() !== '') return value;
  }
  return undefined;
}

function textValue(record, names, fallback) {
  const value = firstValue(record, names);
  if (value === undefined || value === null) return fallback === undefined ? '' : String(fallback);
  return String(value).trim();
}

function numberValue(value) {
  const n = parseFloat(value);
  return Number.isFinite(n) ? n : 0;
}

function missing(fields) {
  return { needs_more_information: true, missing: fields };
}

function textMessage(receiveId, text) {
  return {
    receive_id: receiveId,
    msg_type: 'text',
    content: JSON.stringify({ text })
  };
}

function parseContent(raw) {
  if (!raw) return {};
  if (typeof raw === 'object') return raw;
  try {
    return JSON.parse(String(raw));
  } catch (_) {
    return {};
  }
}

function parseEvent(input) {
  const body = source(input || {});
  if (body.type === 'url_verification') {
    return {
      route: 'challenge',
      challenge: body.challenge,
      webhook: { body: { challenge: body.challenge } }
    };
  }

  if (body.type === 'card' && body.action && body.action.value && body.action.value.submission_id) {
    return { route: 'ignore', reason: 'forwarded_cn_card' };
  }

  const event = body.event || {};
  const message = event.message || {};
  const sender = event.sender || {};
  const senderId = sender.sender_id || {};
  const msgType = message.message_type || '';
  const content = parseContent(message.content || '{}');
  const chatId = message.chat_id || '';
  const msgId = message.message_id || '';
  const userId = senderId.user_id || '';
  const openId = senderId.open_id || '';
  const chatType = message.chat_type || '';

  if (chatType !== 'p2p') return { route: 'ignore', reason: 'group_disabled_dm_only' };
  if ((sender.sender_type || '') === 'app') return { route: 'ignore', reason: 'bot_self' };

  if (msgType === 'file' || msgType === 'image') {
    const fileKey = content.file_key || content.image_key || '';
    const fileName = content.file_name || ('invoice.' + (msgType === 'image' ? 'jpg' : 'pdf'));
    return {
      route: 'file',
      user_id: userId,
      open_id: openId,
      chat_id: chatId,
      msg_id: msgId,
      msg_type: msgType,
      file_key: fileKey,
      file_name: fileName
    };
  }

  if (msgType === 'text') {
    const text = String(content.text || '').toLowerCase();
    const clearKeywords = ['清空', '取消', 'clear', 'cancel'];
    const submitKeywords = ['提交', '报销', '完成', 'submit', 'done', 'go'];
    for (const kw of clearKeywords) {
      if (text.includes(kw)) return { route: 'clear', user_id: userId, open_id: openId, chat_id: chatId, msg_id: msgId };
    }
    for (const kw of submitKeywords) {
      if (text.includes(kw)) return { route: 'submit', user_id: userId, open_id: openId, chat_id: chatId, msg_id: msgId };
    }
  }

  return { route: 'ignore', reason: 'unsupported_message' };
}

function buildStatusMessage(input) {
  const record = source(input || {});
  const status = textValue(record, ['status', 'message_status', 'messageStatus', 'type']);
  if (!status) return missing(['status']);

  let path = MESSAGE_PATH_CHAT;
  let receiveId = '';
  let text = '';

  if (status === 'file_received') {
    const chatId = textValue(record, ['chat_id', 'chatId', 'receive_id', 'receiveId']);
    const fileName = textValue(record, ['file_name', 'fileName']);
    const count = firstValue(record, ['count', 'pending_count', 'pendingCount']);
    const missingFields = [];
    if (!chatId) missingFields.push('chat_id');
    if (!fileName) missingFields.push('file_name');
    if (count === undefined) missingFields.push('count');
    if (missingFields.length) return missing(missingFields);
    receiveId = chatId;
    const isDuplicate = !!record.is_duplicate;
    const ocrFailed = !!record.ocr_failed;
    const prefix = isDuplicate ? '⚠️ DUPLICATE — ' : (ocrFailed ? '⚠️ ' : '✅ ');
    text = prefix + 'Received ' + fileName
      + (ocrFailed ? ' (OCR failed, manual input needed)' : ' — ' + textValue(record, ['ocr_vendor', 'ocrVendor'], 'Unknown') + ' ' + textValue(record, ['ocr_amount', 'ocrAmount'], '?') + ' ' + textValue(record, ['ocr_currency', 'ocrCurrency'], '?'))
      + (isDuplicate ? '\n🔴 Duplicate invoice detected! Invoice# ' + textValue(record, ['invoice_number', 'invoiceNumber']) + ' already in pending. Send "清空/clear" to reset.' : '')
      + '\n📎 Pending: ' + count + ' file(s). Send "提交/submit" when ready.'
      + (record.stale_warning ? '\n⏰ Warning: ' + textValue(record, ['stale_count', 'staleCount'], '0') + ' file(s) pending > 24h. Send "提交/submit" or "清空/clear".' : '');
  } else if (status === 'no_pending') {
    receiveId = textValue(record, ['chat_id', 'chatId', 'receive_id', 'receiveId']);
    if (!receiveId) return missing(['chat_id']);
    text = 'No pending files. Please send invoice files first. / 没有待处理的文件，请先发送发票文件。';
  } else if (status === 'cleared') {
    receiveId = textValue(record, ['chat_id', 'chatId', 'receive_id', 'receiveId']);
    const clearedCount = firstValue(record, ['cleared_count', 'clearedCount']);
    const missingFields = [];
    if (!receiveId) missingFields.push('chat_id');
    if (clearedCount === undefined) missingFields.push('cleared_count');
    if (missingFields.length) return missing(missingFields);
    text = 'Pending files cleared (' + clearedCount + ' removed) / 已清空暂存文件（' + clearedCount + ' 个）';
  } else if (status === 'cooldown') {
    path = MESSAGE_PATH_OPEN;
    receiveId = textValue(record, ['open_id', 'openId', 'receive_id', 'receiveId']);
    if (!receiveId) return missing(['open_id']);
    text = '上一笔报销刚提交，正在处理中。同一个用户 1 分钟内不能重复提交，请稍等。';
  } else {
    return { skip: true, reason: 'unsupported status' };
  }

  return {
    message_type: 'lark_text_message',
    status,
    lark: {
      path,
      body: textMessage(receiveId, text)
    }
  };
}

function aggregateFromPending(record) {
  const pending = Array.isArray(record.pending) ? record.pending : [];
  if (!pending.length) return Object.assign({}, record);

  const byCurrency = {};
  for (const p of pending) {
    const cur = (p.ocr && p.ocr.currency) || 'UNKNOWN';
    if (!byCurrency[cur]) byCurrency[cur] = { items: [], total: 0 };
    byCurrency[cur].items.push(p);
    byCurrency[cur].total += parseFloat((p.ocr && p.ocr.amount) || 0);
  }

  const currencies = Object.keys(byCurrency);
  const mixedCurrency = currencies.length > 1;
  const seenInvoiceNumbers = {};
  let duplicateCount = 0;
  let ocrSummary = '';
  let combinedDescription = '';
  const allFileTokens = [];
  const allInvoiceNumbers = [];
  const allVendors = [];

  for (let i = 0; i < pending.length; i++) {
    const p = pending[i];
    const inv = p.ocr || {};
    const invNum = String(inv.invoice_number || '').trim();
    let dupFlag = !!p.is_duplicate;
    if (invNum && invNum !== 'N/A' && invNum !== 'null') {
      if (seenInvoiceNumbers[invNum.toLowerCase()]) {
        dupFlag = true;
        duplicateCount++;
      }
      seenInvoiceNumbers[invNum.toLowerCase()] = true;
    }
    ocrSummary += '\n[Invoice ' + (i + 1) + '] ' + (p.file_name || '') + (dupFlag ? ' ⚠️ DUPLICATE' : '') + '\n';
    ocrSummary += '  Vendor:       ' + (inv.vendor || '?') + '\n';
    ocrSummary += '  Amount:       ' + (inv.amount || '?') + ' ' + (inv.currency || '?') + '\n';
    ocrSummary += '  Date:         ' + (inv.date || '?') + '\n';
    ocrSummary += '  Invoice#:     ' + (inv.invoice_number || '?') + '\n';
    ocrSummary += '  Subscription: ' + (inv.subscription_type || 'N/A') + '\n';
    ocrSummary += '  Period:       ' + (inv.usage_period || 'N/A') + '\n';
    ocrSummary += '  Description:  ' + (inv.description || '?') + '\n';
    if (p.ocr_failed) ocrSummary += '  ⚠️ OCR FAILED — manual input needed\n';
    if (dupFlag) ocrSummary += '  🔴 DUPLICATE INVOICE — same invoice number as another pending file\n';

    const parts = [(dupFlag ? '[DUPLICATE] ' : '') + (inv.vendor || '')];
    if (inv.invoice_number && inv.invoice_number !== 'N/A') parts.push('Inv# ' + inv.invoice_number);
    if (inv.amount) parts.push(inv.amount + ' ' + (inv.currency || ''));
    if (inv.subscription_type && inv.subscription_type !== 'null' && inv.subscription_type !== 'N/A') parts.push(inv.subscription_type);
    if (inv.usage_period && inv.usage_period !== 'null' && inv.usage_period !== 'N/A') parts.push(inv.usage_period);
    if (inv.description && inv.description !== inv.vendor) parts.push(inv.description);
    combinedDescription += (i > 0 ? '\n' : '') + '[' + (i + 1) + '] ' + parts.join(' | ');

    if (p.file_token) allFileTokens.push(p.file_token);
    if (inv.invoice_number && inv.invoice_number !== 'N/A') allInvoiceNumbers.push(inv.invoice_number);
    if (inv.vendor && inv.vendor !== 'Unknown') allVendors.push(inv.vendor);
  }

  if (duplicateCount > 0) ocrSummary = '⚠️ WARNING: ' + duplicateCount + ' duplicate invoice(s) detected!\n' + ocrSummary;
  const primaryCurrency = mixedCurrency ? 'MIXED' : (currencies[0] || 'SGD');
  const totalAmount = mixedCurrency ? 0 : ((byCurrency[primaryCurrency] && byCurrency[primaryCurrency].total) || 0);
  const firstDate = (pending[0] && pending[0].ocr && pending[0].ocr.date)
    || textValue(record, ['first_date', 'firstDate', 'fallback_date', 'fallbackDate', 'receipt_date', 'receiptDate']);

  return Object.assign({}, record, {
    count: record.count !== undefined ? record.count : pending.length,
    ocr_summary: record.ocr_summary || ocrSummary,
    combined_description: record.combined_description || combinedDescription,
    all_file_tokens: Array.isArray(record.all_file_tokens) ? record.all_file_tokens : allFileTokens,
    all_invoice_numbers: Array.isArray(record.all_invoice_numbers) ? record.all_invoice_numbers : allInvoiceNumbers,
    all_vendors: Array.isArray(record.all_vendors) ? record.all_vendors : allVendors,
    primary_currency: record.primary_currency || primaryCurrency,
    total_amount: record.total_amount !== undefined ? record.total_amount : totalAmount,
    first_date: record.first_date || record.firstDate || firstDate,
    mixed_currency: record.mixed_currency !== undefined ? !!record.mixed_currency : mixedCurrency,
    has_ocr_failures: record.has_ocr_failures !== undefined ? !!record.has_ocr_failures : pending.some(p => p.ocr_failed),
    has_duplicates: record.has_duplicates !== undefined ? !!record.has_duplicates : duplicateCount > 0,
    duplicate_count: record.duplicate_count !== undefined ? record.duplicate_count : duplicateCount
  });
}

function buildReviewPackage(input) {
  const record = aggregateFromPending(source(input || {}));
  const submissionId = textValue(record, ['submission_id', 'submissionId']);
  if (!submissionId) return missing(['submission_id']);

  const pendingFiles = Array.isArray(record.pending) ? record.pending : [];
  const formUrl = REVIEW_FORM_BASE_URL + submissionId;
  const headerText = '📎 New reimbursement — ' + pendingFiles.length + ' file(s) from '
    + (record.employee_name || record.submitter_nickname || 'submitter')
    + (record.has_ocr_failures ? ' ⚠️ OCR failed on some files' : '')
    + '\nOriginals below. Review link follows.';
  const financeText = '📋 New Reimbursement (' + (record.count || pendingFiles.length) + ' invoices)\n'
    + 'From: ' + (record.employee_name || '') + ' (' + (record.submitter_email || '') + ')\n'
    + (record.ocr_summary || '') + '\n'
    + (record.mixed_currency ? '⚠️ MIXED CURRENCIES\n' : 'Total: ' + (record.total_amount || 0) + ' ' + (record.primary_currency || 'SGD') + '\n')
    + (record.has_ocr_failures ? '⚠️ Some OCR failed\n' : '')
    + (record.has_duplicates ? '🔴 DUPLICATES DETECTED\n' : '')
    + '\n📝 Review & Submit: ' + formUrl;

  const forwardMessages = pendingFiles.filter(p => p && p.msg_id).map(p => ({
    path: '/open-apis/im/v1/messages/' + p.msg_id + '/forward?receive_id_type=open_id',
    body: { receive_id: REVIEWER_OPEN_ID }
  }));

  return {
    message_type: 'employee_reimbursement_review_package',
    submission_id: submissionId,
    form_url: formUrl,
    reviewer_open_id: REVIEWER_OPEN_ID,
    aggregate: {
      count: record.count || pendingFiles.length,
      primary_currency: record.primary_currency || 'SGD',
      total_amount: record.total_amount || 0,
      mixed_currency: !!record.mixed_currency,
      has_ocr_failures: !!record.has_ocr_failures,
      has_duplicates: !!record.has_duplicates,
      duplicate_count: record.duplicate_count || 0
    },
    lark: {
      reviewerHeader: {
        path: MESSAGE_PATH_OPEN,
        body: textMessage(REVIEWER_OPEN_ID, headerText)
      },
      forwardMessages,
      financeMessage: {
        path: MESSAGE_PATH_OPEN,
        body: textMessage(REVIEWER_OPEN_ID, financeText)
      }
    }
  };
}

function reviewValue(reviewRaw, label) {
  const variants = [
    label,
    label.toLowerCase(),
    label.replace(/\s+/g, '_').toLowerCase(),
    label.replace(/\s+/g, '').toLowerCase()
  ];
  for (const v of variants) {
    if (reviewRaw[v] !== undefined && reviewRaw[v] !== null && reviewRaw[v] !== '') return reviewRaw[v];
  }
  for (const key of Object.keys(reviewRaw)) {
    if (key.toLowerCase().replace(/[_\s-]/g, '') === label.toLowerCase().replace(/[_\s-]/g, '')) return reviewRaw[key];
  }
  return null;
}

function normalizeDate(value) {
  if (!value) return '';
  const raw = String(value).trim();
  const d = new Date(raw);
  return !Number.isNaN(d.getTime()) ? d.toISOString().split('T')[0] + 'T00:00:00Z' : raw + 'T00:00:00Z';
}

function resolveRelatedApproval(record, reviewRaw) {
  const direct = textValue(record, ['related_approval_instance_code', 'relatedApprovalInstanceCode', 'related_approval_id', 'relatedApprovalId']);
  if (direct) return { value: direct.toUpperCase() };
  const input = String(reviewValue(reviewRaw, 'Related Approval') || '').trim();
  if (!input) return { value: null };
  const uuidRe = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  const serialRe = /^[0-9]{12}$/;
  if (uuidRe.test(input)) return { value: input.toUpperCase() };
  if (serialRe.test(input)) return { missing: ['related_approval_instance_code'], reason: 'related approval serial must be resolved by Aevatar before payload build' };
  return { invalid: true, errors: ['Related Approval format not recognized: ' + input] };
}

function buildApprovalInstance(input) {
  const record = aggregateFromPending(source(input || {}));
  const reviewRaw = record.review || record.review_fields || record.reviewFields || record;
  const applicantId = textValue(record, ['submitter_user_id', 'submitterUserId', 'user_id', 'userId']);
  const pending = Array.isArray(record.pending) ? record.pending : [];
  const missingFields = [];
  if (!applicantId) missingFields.push('submitter_user_id');
  if (!pending.length) missingFields.push('pending');
  if (missingFields.length) return missing(missingFields);

  const excludeStr = String(reviewValue(reviewRaw, 'Exclude Invoices') || '').trim();
  const excludeSet = new Set();
  if (excludeStr) {
    excludeStr.split(/[,;\s]+/).forEach(s => {
      const n = parseInt(String(s).trim(), 10);
      if (!Number.isNaN(n) && n > 0) excludeSet.add(n);
    });
  }

  const kept = [];
  const keptTokens = [];
  let keptDescription = '';
  let keptTotal = 0;
  const autoExcludedDupes = [];
  for (let i = 0; i < pending.length; i++) {
    if (excludeSet.has(i + 1)) continue;
    const p = pending[i];
    if (p && p.is_duplicate) {
      excludeSet.add(i + 1);
      autoExcludedDupes.push(i + 1);
      continue;
    }
    const inv = p.ocr || {};
    kept.push(p);
    if (p.file_token) keptTokens.push(p.file_token);
    keptDescription += (kept.length > 1 ? '\n' : '') + '[' + kept.length + '] ' + (inv.description || '');
    keptTotal += parseFloat(inv.amount || 0);
  }

  if (!kept.length) return { invalid: true, errors: ['All invoices excluded. Nothing to submit.'] };

  const category = reviewValue(reviewRaw, 'Reimbursement Category') || '技术服务费';
  const categoryId = CATEGORY_MAP[category] || 'lwkkktxl-xsh7nzjrjb-9';
  const currency = String(reviewValue(reviewRaw, 'Currency') || 'SGD').toUpperCase();
  const currencyId = CURRENCY_MAP[currency] || 'lwpzlrza-w81tf7okwq-0';
  const reviewAmount = reviewValue(reviewRaw, 'Amount');
  const amount = reviewAmount ? parseFloat(reviewAmount) : keptTotal;
  const rawDate = reviewValue(reviewRaw, 'Receipt Date') || record.first_date || textValue(record, ['receipt_date', 'receiptDate', 'fallback_date', 'fallbackDate']);
  const dateISO = normalizeDate(rawDate);
  const reviewDesc = reviewValue(reviewRaw, 'Expense Description');
  const description = reviewDesc || keptDescription;
  const department = reviewValue(reviewRaw, 'Department') || record.employee_department || 'Finance';
  const deptHeadId = record.employee_department_head_id || applicantId;
  const payeeName = reviewValue(reviewRaw, 'Payee Name') || record.employee_name || '';
  const bankName = reviewValue(reviewRaw, 'Bank Name') || record.employee_bank_name || '';
  const bankAccount = reviewValue(reviewRaw, 'Bank Account') || record.employee_bank_account || '';
  const remark = reviewValue(reviewRaw, 'Remark') || '';

  const related = resolveRelatedApproval(record, reviewRaw);
  if (related.missing) return { needs_more_information: true, missing: related.missing, reason: related.reason };
  if (related.invalid) return { invalid: true, errors: related.errors };

  const row = [
    { id: WIDGETS.row_department, type: 'input', value: department },
    { id: WIDGETS.row_dept_head, type: 'contact', value: [deptHeadId] },
    { id: WIDGETS.row_date, type: 'date', value: dateISO },
    { id: WIDGETS.row_category, type: 'radioV2', value: categoryId },
    { id: WIDGETS.row_short_description, type: 'input', value: description.substring(0, 200) },
    { id: WIDGETS.row_description, type: 'textarea', value: description },
    { id: WIDGETS.row_currency, type: 'radioV2', value: currencyId },
    { id: WIDGETS.row_amount, type: 'amount', value: amount, currency },
    { id: WIDGETS.row_payee_name, type: 'input', value: payeeName },
    { id: WIDGETS.row_bank_name, type: 'input', value: bankName },
    { id: WIDGETS.row_bank_account, type: 'input', value: bankAccount },
    { id: WIDGETS.row_attachment, type: 'attachmentV2', value: keptTokens }
  ];

  const formData = [{ id: WIDGETS.field_list, type: 'fieldList', value: [row] }];
  if (related.value) formData.push({ id: WIDGETS.related_approval, type: 'connect', value: [related.value] });
  const remarkValue = remark ? remark + '\n' + AI_DISCLAIMER : AI_DISCLAIMER;
  formData.push({ id: WIDGETS.remarks, type: 'input', value: remarkValue });

  const approvalBody = {
    approval_code: APPROVAL_CODE,
    user_id: applicantId,
    form: JSON.stringify(formData)
  };
  const excludedMsg = excludeSet.size > 0
    ? ' (excluded ' + excludeSet.size + ' invoice(s)' + (autoExcludedDupes.length ? ', incl. ' + autoExcludedDupes.length + ' auto-skipped dupe(s)' : '') + ')'
    : '';

  return {
    message_type: 'lark_approval_instance',
    approval_body: JSON.stringify(approvalBody),
    approvalBody,
    form: formData,
    applicant_id: applicantId,
    category,
    currency,
    amount,
    payee_name: payeeName,
    kept_count: kept.length,
    excluded_count: excludeSet.size,
    excluded_msg: excludedMsg,
    lark: {
      path: APPROVAL_PATH,
      body: approvalBody
    }
  };
}

function approvalSerial(record) {
  const detail = record.approval_detail || record.approvalDetail || record;
  const data = detail.data || {};
  return textValue(record, ['serial_number', 'serialNumber', 'lark_no', 'larkNo'])
    || data.serial_number
    || textValue(record, ['instance_code', 'instanceCode'])
    || data.instance_code;
}

function buildResultMessages(input) {
  const record = source(input || {});
  const chatId = textValue(record, ['chat_id', 'chatId']);
  const submitterOpenId = textValue(record, ['submitter_open_id', 'submitterOpenId', 'open_id', 'openId']);
  const count = firstValue(record, ['count', 'kept_count', 'keptCount']);
  const amount = firstValue(record, ['amount']);
  const currency = textValue(record, ['currency']);
  const serial = approvalSerial(record);
  const missingFields = [];
  if (!chatId) missingFields.push('chat_id');
  if (!submitterOpenId) missingFields.push('submitter_open_id');
  if (count === undefined) missingFields.push('count');
  if (amount === undefined) missingFields.push('amount');
  if (!currency) missingFields.push('currency');
  if (!serial) missingFields.push('serial_number');
  if (missingFields.length) return missing(missingFields);

  const excludedMsg = textValue(record, ['excluded_msg', 'excludedMsg']);
  const payeeName = textValue(record, ['submitter_nickname', 'submitterNickname'])
    || textValue(record, ['payee_name', 'payeeName']);
  const ocrSummary = record.ocr_summary || record.ocrSummary || '';
  const chatText = '✅ Reimbursement submitted! / 报销审批已提交！\n'
    + '📋 ' + count + ' invoice(s)' + excludedMsg + '\n'
    + '💰 ' + amount + ' ' + currency + '\n'
    + '👤 ' + payeeName + '\n'
    + '📎 Lark No: ' + serial;
  const submitterText = '✅ Your reimbursement has been submitted! / 你的报销已提交！\n\n'
    + 'Invoices: ' + count + excludedMsg + '\n'
    + 'Amount: ' + amount + ' ' + currency + '\n'
    + 'Lark No: ' + serial + '\n\n'
    + ocrSummary;

  return {
    message_type: 'employee_reimbursement_result_messages',
    serial_number: serial,
    lark: {
      chatMessage: {
        path: MESSAGE_PATH_CHAT,
        body: textMessage(chatId, chatText)
      },
      submitterMessage: {
        path: MESSAGE_PATH_OPEN,
        body: textMessage(submitterOpenId, submitterText)
      }
    }
  };
}

function buildPayload(input) {
  const root = input || {};
  const record = source(root);
  const mode = root.mode || record.mode || 'build_approval_instance';
  if (mode === 'parse_event') return parseEvent(root);
  if (mode === 'build_status_message') return buildStatusMessage(root);
  if (mode === 'build_review_package') return buildReviewPackage(root);
  if (mode === 'build_approval_instance') return buildApprovalInstance(root);
  if (mode === 'build_result_messages') return buildResultMessages(root);
  return { skip: true, reason: 'unsupported mode' };
}

if (require.main === module) {
  process.stdout.write(`${JSON.stringify(buildPayload(readInput()), null, 2)}\n`);
}

module.exports = { buildPayload };
