#!/usr/bin/env node
'use strict';

const fs = require('fs');

const DEFAULT_APPROVAL_CODE = 'F640097D-0A68-47C1-A7BC-86659BC4B06F';
const DEFAULT_ENTITY = 'ChronoAI Pte Ltd (法币支付)';
const AI_DISCLAIMER = 'This approval was auto-generated by AI invoice recognition system. Data was reviewed and confirmed by the submitter before submission.';

const PAYMENT_TYPE_MAP = {
  'ChronoAI Pte Ltd (法币支付)': 'lwpsdr33-27z0rv3m3t4-0',
  'ECHO AI Pte Ltd（法币支付）': 'm985jjql-nv5p6wxbf3-1',
  'Portkey Singapore Entity (法币支付)': 'lwpsdr33-1ogx09m8w4w-0',
  'Eregion Labs Pte Ltd（法币支付）': 'lwpu4gg8-7utwc7j0g5-1',
  'AELF INVEST': 'lwpsdr33-zgezrnen1e-0',
  'DigitalAsset Payment': 'lwpsqbd0-edoqopnuje7-1'
};

const NO_MARKETING = 'm1er13p8-jy4c1eb1le-0';
const NO_HR = 'miig2pwk-4bx8l7d96pf-0';
const NO_CONTRACT = 'lwpsq1d7-72ixwmka1jh-0';
const YES_CONTRACT = 'lwpsq1d7-v8f220gwhp-0';
const WAY_BANK_TRANSFER = 'lwpsti1z-5ogmo0ul3vb-0';

function readInput() {
  const text = fs.readFileSync(0, 'utf8');
  return text.trim() ? JSON.parse(text) : {};
}

function source(input) {
  return input && input.body && typeof input.body === 'object' ? input.body : input;
}

function firstValue(record, names) {
  for (const name of names) {
    const value = record ? record[name] : undefined;
    if (value !== undefined && value !== null && String(value).trim() !== '') return value;
  }
  return undefined;
}

function labelVariants(label) {
  return [
    label,
    label.toLowerCase(),
    label.replace(/\s+/g, '_'),
    label.replace(/\s+/g, '_').toLowerCase(),
    label.replace(/\s+/g, '-'),
    label.replace(/\s+/g, '-').toLowerCase(),
    label.replace(/\s+/g, ''),
    label.replace(/\s+/g, '').toLowerCase()
  ];
}

function getReview(reviewRaw, label) {
  const variants = labelVariants(label);
  for (const variant of variants) {
    const value = reviewRaw ? reviewRaw[variant] : undefined;
    if (value !== undefined && value !== null && String(value).trim() !== '') return value;
  }
  return undefined;
}

function asArray(value) {
  if (Array.isArray(value)) return value;
  if (value === undefined || value === null || value === '') return [];
  return [value];
}

function normalizeInvoices(record) {
  const nested = record.parsed && Array.isArray(record.parsed.invoices) ? record.parsed.invoices : undefined;
  const ocrNested = record.ocr && Array.isArray(record.ocr.invoices) ? record.ocr.invoices : undefined;
  const direct = Array.isArray(record.invoices) ? record.invoices : undefined;
  const single = record.invoice && typeof record.invoice === 'object' ? [record.invoice] : undefined;
  return (direct || nested || ocrNested || single || []).map((invoice) => invoice || {});
}

function normalizeReview(record) {
  return record.review || record.reviewRaw || record.review_raw || record.reviewFields || record.review_fields || record;
}

function normalizeAttachments(record) {
  const upload = record.upload || record.uploadInvoiceToLark || record.upload_invoice_to_lark || {};
  const values = record.attachments || upload.attachments || [];
  return asArray(values).map((attachment) => {
    if (typeof attachment === 'string') return { file_token: attachment };
    return attachment || {};
  });
}

function normalizeApplicantOpenId(record) {
  const direct = firstValue(record, [
    'applicantOpenId',
    'applicant_open_id',
    'applicantUserId',
    'applicant_user_id',
    'open_id',
    'openId',
    'user_id',
    'userId'
  ]);
  if (direct !== undefined) return String(direct).trim();

  const applicant = record.applicant || {};
  const applicantValue = firstValue(applicant, ['open_id', 'openId', 'user_id', 'userId']);
  if (applicantValue !== undefined) return String(applicantValue).trim();

  const lookup = record.lookupApplicant || record.lookup_applicant || {};
  const userList = lookup.data && Array.isArray(lookup.data.user_list) ? lookup.data.user_list : [];
  const firstUser = userList[0] || {};
  const lookupValue = firstValue(firstUser, ['open_id', 'openId', 'user_id', 'userId']);
  return lookupValue !== undefined ? String(lookupValue).trim() : undefined;
}

function normalizeDeptHeadId(record, applicantOpenId) {
  const direct = firstValue(record, [
    'deptHeadId',
    'dept_head_id',
    'departmentHeadId',
    'department_head_id',
    'departmentHeadOpenId',
    'department_head_open_id',
    'leader_user_id',
    'leaderUserId'
  ]);
  if (direct !== undefined) return String(direct).trim();
  const leader = record.departmentHead || record.department_head || {};
  const leaderValue = firstValue(leader, ['open_id', 'openId', 'user_id', 'userId']);
  if (leaderValue !== undefined) return String(leaderValue).trim();
  return applicantOpenId;
}

function normalizeRelatedApprovalId(record, reviewRaw) {
  const direct = firstValue(record, [
    'relatedApprovalId',
    'related_approval_id',
    'relatedApprovalInstanceCode',
    'related_approval_instance_code',
    'relatedInstanceCode',
    'related_instance_code'
  ]);
  const reviewValue = getReview(reviewRaw, 'Related Approval ID') || getReview(reviewRaw, 'Related Approval');
  const raw = direct !== undefined ? direct : reviewValue;
  if (raw === undefined || raw === null || String(raw).trim() === '') return { value: null };

  const value = String(raw).trim();
  const uuidRe = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  const serialRe = /^\d{12}$/;
  if (uuidRe.test(value)) return { value: value.toUpperCase() };
  if (serialRe.test(value)) return { missing: ['relatedApprovalId'], reason: 'related approval serial must be resolved to a Lark instance id before payload building' };
  return { missing: ['relatedApprovalId'], reason: 'related approval value is not a Lark instance id' };
}

function parseAmounts(value) {
  if (Array.isArray(value)) return value.map((item) => String(item).trim());
  if (value === undefined || value === null) return [];
  return String(value).split(',').map((item) => item.trim());
}

function parseIsoDate(value) {
  if (value === undefined || value === null || String(value).trim() === '') return null;
  const text = String(value).trim();
  const match = text.match(/^(\d{4})-(\d{2})-(\d{2})/);
  if (!match) return null;
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  if (month < 1 || month > 12 || day < 1 || day > daysInMonth(year, month)) return null;
  return `${match[1]}-${match[2]}-${match[3]}`;
}

function isLeapYear(year) {
  return year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
}

function daysInMonth(year, month) {
  if (month === 2) return isLeapYear(year) ? 29 : 28;
  return [4, 6, 9, 11].includes(month) ? 30 : 31;
}

function pad2(value) {
  return String(value).padStart(2, '0');
}

function addDaysIsoDate(isoDate, days) {
  const match = isoDate.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  let year = Number(match[1]);
  let month = Number(match[2]);
  let day = Number(match[3]) + days;
  while (day > daysInMonth(year, month)) {
    day -= daysInMonth(year, month);
    month += 1;
    if (month > 12) {
      month = 1;
      year += 1;
    }
  }
  while (day < 1) {
    month -= 1;
    if (month < 1) {
      month = 12;
      year -= 1;
    }
    day += daysInMonth(year, month);
  }
  return `${year}-${pad2(month)}-${pad2(day)}`;
}

function amountForInvoice(invoice, reviewedAmounts, index) {
  const reviewed = reviewedAmounts[index];
  const raw = reviewed !== undefined && reviewed !== '' ? reviewed : invoice.amount;
  if (raw === undefined || raw === null || String(raw).trim() === '') return null;
  const parsed = parseFloat(String(raw).trim());
  return Number.isFinite(parsed) ? parsed : null;
}

function compactMissing(values) {
  return Array.from(new Set(values.filter(Boolean)));
}

function buildPayload(input) {
  const record = source(input || {});
  const mode = record.mode || 'build_approval';
  if (mode !== 'build_approval') return { skip: true, reason: 'unsupported mode' };

  const reviewRaw = normalizeReview(record);
  const invoices = normalizeInvoices(record);
  const applicantOpenId = normalizeApplicantOpenId(record);
  const department = String(getReview(reviewRaw, 'Department') || firstValue(record, ['department', 'Department']) || '').trim();
  const sharedCurrency = String(getReview(reviewRaw, 'Currency') || firstValue(record, ['currency', 'Currency']) || 'SGD').toUpperCase();
  const sharedEntity = String(getReview(reviewRaw, 'Payment Entity') || firstValue(record, ['paymentEntity', 'payment_entity', 'Payment Entity']) || DEFAULT_ENTITY).trim();
  const approvalCode = String(firstValue(record, ['approvalCode', 'approval_code']) || DEFAULT_APPROVAL_CODE).trim();
  const executionDate = parseIsoDate(firstValue(record, ['executionDate', 'execution_date', 'today']));
  const reviewedVendor = String(getReview(reviewRaw, 'Vendor') || firstValue(record, ['vendor', 'Vendor']) || '').trim();
  const reviewedAmounts = parseAmounts(getReview(reviewRaw, 'Amount') || firstValue(record, ['amounts', 'amount', 'Amount']));
  const remark = String(getReview(reviewRaw, 'Remark') || firstValue(record, ['remark', 'Remark']) || (record.parsed && record.parsed.remark) || '').trim();
  const relatedApproval = normalizeRelatedApprovalId(record, reviewRaw);

  const missing = [];
  if (!invoices.length) missing.push('invoices');
  if (!applicantOpenId) missing.push('applicantOpenId');
  if (!department) missing.push('department');
  if (relatedApproval.missing) missing.push(...relatedApproval.missing);

  for (let index = 0; index < invoices.length; index += 1) {
    const invoice = invoices[index];
    const rowDate = parseIsoDate(invoice.date) || executionDate;
    const rowAmount = amountForInvoice(invoice, reviewedAmounts, index);
    const rowVendor = reviewedVendor || String(invoice.vendor || '').trim();
    if (!rowDate) missing.push(`invoices[${index}].date`);
    if (rowAmount === null) missing.push(`invoices[${index}].amount`);
    if (!rowVendor) missing.push(`invoices[${index}].vendor`);
  }

  const finalMissing = compactMissing(missing);
  if (finalMissing.length) {
    const result = { needs_more_information: true, missing: finalMissing };
    if (relatedApproval.reason) result.reason = relatedApproval.reason;
    return result;
  }

  const relatedApprovalId = relatedApproval.value;
  const deptHeadId = normalizeDeptHeadId(record, applicantOpenId);
  const deptHeadSource = String(firstValue(record, ['deptHeadSource', 'dept_head_source']) || (deptHeadId === applicantOpenId ? 'self' : 'input')).trim();
  const paymentType = PAYMENT_TYPE_MAP[sharedEntity] || PAYMENT_TYPE_MAP[DEFAULT_ENTITY];
  const contractOption = relatedApprovalId ? YES_CONTRACT : NO_CONTRACT;

  function buildRow(invoice, index) {
    const isAelfInvest = paymentType === PAYMENT_TYPE_MAP['AELF INVEST'];
    const isDigitalAsset = paymentType === PAYMENT_TYPE_MAP['DigitalAsset Payment'];
    const isCryptoPath = isAelfInvest || isDigitalAsset;
    const invoiceDate = parseIsoDate(invoice.date) || executionDate;
    const amountValue = amountForInvoice(invoice, reviewedAmounts, index);
    const perInvoiceDesc = getReview(reviewRaw, `Description ${index + 1}`);
    const finalDesc = String(perInvoiceDesc || invoice.description || `Payment to ${invoice.vendor || 'vendor'}`);
    const descriptionText = `${finalDesc} (Invoice: ${invoice.invoice_number || 'N/A'})`;
    const row = [
      { id: 'widget17168644567560001', type: 'contact', value: [deptHeadId] },
      { id: 'widget17168638060470001', type: 'radioV2', value: paymentType },
      { id: 'widget17270803199920001', type: 'radioV2', value: NO_MARKETING },
      { id: 'widget17643090840670001', type: 'radioV2', value: NO_HR },
      { id: 'widget17168643792430001', type: 'radioV2', value: contractOption }
    ];
    if (relatedApprovalId) row.push({ id: 'widget17168655594420001', type: 'connect', value: [relatedApprovalId] });
    row.push(
      { id: 'widget17168645326090001', type: 'textarea', value: descriptionText },
      { id: 'widget17168645408360001', type: 'radioV2', value: WAY_BANK_TRANSFER }
    );
    if (isCryptoPath) {
      row.push({ id: 'widget17168648709360001', type: 'number', value: String(amountValue) });
      if (isDigitalAsset) {
        row.push({
          id: 'widget17241241332240001',
          type: 'radioV2',
          value: amountValue < 5000
            ? 'm01uzre5-3vbzwd8wl3b-0'
            : (amountValue <= 50000 ? 'm01uzre5-pjmscdzhzbr-0' : 'm01uzre5-xcbztagc13-0')
        });
      }
    } else {
      row.push({
        id: 'widget17168648705100001',
        type: 'amount',
        value: amountValue,
        currency: sharedCurrency,
        ext: { currency: sharedCurrency, currencyRange: ['USD', 'CNY', 'SGD'] }
      });
    }
    row.push(
      { id: 'widget16487160384360001', type: 'date', value: `${invoiceDate}T00:00:00Z` },
      { id: 'widget17168661650480001', type: 'input', value: reviewedVendor || invoice.vendor || 'Unknown' },
      { id: 'widget17168661652050001', type: 'input', value: invoice.bank_name || 'TBD - please fill' },
      { id: 'widget17168661653930001', type: 'input', value: invoice.bank_account || 'TBD - please fill' },
      { id: 'widget17168661664870001', type: 'input', value: invoice.swift_code || 'TBD' },
      { id: 'widget17168769083410001', type: 'textarea', value: finalDesc },
      { id: 'widget17168764909530001', type: 'date', value: `${addDaysIsoDate(invoiceDate, 30)}T00:00:00Z` }
    );
    return row;
  }

  const form = [{ id: 'widget17168633868040001', type: 'fieldList', value: invoices.map(buildRow) }];
  const fileTokens = normalizeAttachments(record).map((attachment) => (
    firstValue(attachment, ['file_token', 'fileToken', 'code', 'token'])
  )).filter((token) => token !== undefined && token !== null && String(token).trim() !== '').map((token) => String(token).trim());
  if (fileTokens.length > 0) {
    form.push({ id: 'widget16487161419060001', type: 'attachmentV2', value: fileTokens });
  }

  const remarkValue = remark ? `${remark}\n\n${AI_DISCLAIMER}` : AI_DISCLAIMER;
  form.push({ id: 'widget16487161430270001', type: 'textarea', value: remarkValue });

  const body = {
    approval_code: approvalCode,
    user_id: applicantOpenId,
    form: JSON.stringify(form)
  };

  return {
    message_type: 'lark_approval_instance',
    summary: `Invoice approval for ${invoices.length} invoice${invoices.length === 1 ? '' : 's'}`,
    invoice_count: invoices.length,
    applicant_open_id: applicantOpenId,
    dept_head_id: deptHeadId,
    dept_head_source: deptHeadSource,
    department,
    shared_currency: sharedCurrency,
    shared_entity: sharedEntity,
    related_approval_id: relatedApprovalId,
    form,
    approval_body: JSON.stringify(body),
    lark: {
      path: '/open-apis/approval/v4/instances?user_id_type=user_id',
      body
    }
  };
}

if (require.main === module) {
  process.stdout.write(`${JSON.stringify(buildPayload(readInput()), null, 2)}\n`);
}

module.exports = { buildPayload };
