#!/usr/bin/env node
'use strict';

const fs = require('fs');

const MESSAGE_PATH = '/open-apis/im/v1/messages?receive_id_type=open_id';
const APPROVAL_PATH = '/open-apis/approval/v4/instances?user_id_type=user_id';
const REVIEWER_OPEN_ID = 'ou_3d9067006e9fb8eb8e5fc7b2bb4c6264';
const ADA_USER_ID = 'bfb84d8a';
const JASON_USER_ID = '6b15c721';
const CNY_OPTION = 'lwpzlrza-zoo84ker6o-0';
const APPROVAL_CODE = '599F145B-9E25-4746-A2DA-7B87DB92AD0F';
const FORM_BASE_URL = 'https://n8n.aelf.dev/form/cn-reimbursement-review?submission_id=';
const DISCLAIMER = 'This approval was auto-generated by AI reimbursement recognition system. Data was reviewed and confirmed by Finance before submission.';

const WIDGETS = {
  field_list: 'widget17661255766760001',
  attachment_top: 'widget17165485097290001',
  remarks: 'widget17667289445210001',
  row_department: 'widget17675914385750001',
  row_dept_head: 'widget17165475059790001',
  row_date: 'widget17661256619280001',
  row_category: 'widget17165483685010001',
  row_purpose: 'widget17661277169490001',
  row_currency: 'widget17168759377620001',
  row_amount: 'widget17661271904410001',
  row_bank_card: 'widget17239470147730001',
  row_attachment: 'widget17165484992290001'
};

const CATEGORY_MAP = {
  '技术服务费': 'lwkkktxl-xsh7nzjrjb-9',
  '员工福利': 'lwkkktxl-hsb5k4bhad5-5',
  '差旅费': 'lwkkktx1-a5eycrbdol7-0',
  '办公费': 'lwkkktx1-1lgmf4xvjn2-0',
  Others: 'mjch1lsy-kmowo0xjgxc-3'
};

const VALID_SUBBRANDS = ['aelf network', 'AetherLink', 'Portkey', 'eBridge'];

function readInput() {
  const text = fs.readFileSync(0, 'utf8');
  return text.trim() ? JSON.parse(text) : {};
}

function source(input) {
  return input && input.body && typeof input.body === 'object' ? input.body : input;
}

function firstValue(record, names) {
  for (const name of names) {
    const value = record ? record[name] : undefined;
    if (value !== undefined && value !== null && String(value).trim() !== '') return value;
  }
  return undefined;
}

function textValue(record, names, fallback) {
  const value = firstValue(record, names);
  if (value === undefined || value === null) return fallback === undefined ? '' : String(fallback);
  return String(value).trim();
}

function numberValue(value) {
  const n = parseFloat(value);
  return Number.isFinite(n) ? n : 0;
}

function missing(fields) {
  return { needs_more_information: true, missing: fields };
}

function textMessage(receiveId, text) {
  return {
    receive_id: receiveId,
    msg_type: 'text',
    content: JSON.stringify({ text })
  };
}

function parseMessageText(message) {
  const raw = message && message.content !== undefined ? message.content : '';
  try {
    const parsed = typeof raw === 'string' ? JSON.parse(raw || '{}') : (raw || {});
    return String(parsed.text || '').trim().toLowerCase();
  } catch (_) {
    throw new Error('content_parse_error');
  }
}

function parseEvent(input) {
  const body = source(input || {});
  if (body && body.type === 'card' && body.action && body.action.value && body.action.value.submission_id) {
    return { action: 'card_callback', payload: body };
  }
  if ((body.type || '') === 'url_verification') {
    return {
      action: 'challenge',
      challenge: body.challenge,
      webhook: { body: { challenge: body.challenge } }
    };
  }

  const ev = body.event || {};
  const msg = ev.message || {};
  const sender = ev.sender || {};
  if ((sender.sender_type || '') === 'app') return { action: 'drop', reason: 'bot_self' };
  if (msg.chat_type !== 'p2p') return { action: 'drop', reason: 'not_p2p' };

  const senderOpenId = sender.sender_id && sender.sender_id.open_id;
  if (!senderOpenId) return { action: 'drop', reason: 'no_sender' };

  let text = '';
  let attachments = [];
  try {
    text = parseMessageText(msg);
    const parsed = typeof msg.content === 'string' ? JSON.parse(msg.content || '{}') : (msg.content || {});
    if (msg.message_type === 'image' && parsed.image_key) {
      attachments = [{ kind: 'image', key: parsed.image_key, message_id: msg.message_id }];
    }
    if (msg.message_type === 'file' && parsed.file_key) {
      attachments = [{ kind: 'file', key: parsed.file_key, message_id: msg.message_id }];
    }
  } catch (_) {
    return { action: 'drop', reason: 'content_parse_error' };
  }

  const triggerKeyword = text.includes('submit') || text.includes('提交') || text.includes('清空') || text === 'clear';
  const action = triggerKeyword ? 'trigger' : (attachments.length ? 'buffer_attachment' : 'drop');
  return {
    action,
    open_id: senderOpenId,
    message_id: msg.message_id,
    chat_id: msg.chat_id,
    text,
    attachments
  };
}

function buildStatusMessage(input) {
  const record = source(input || {});
  const status = textValue(record, ['status', 'message_status', 'type']);
  const openId = textValue(record, ['open_id', 'openId', 'receive_id', 'receiveId']);
  const operatorOpenId = textValue(record, ['operator_open_id', 'operatorOpenId', 'open_id', 'openId', 'receive_id', 'receiveId']);
  let receiveId = openId;
  let text = '';

  if (!status) return missing(['status']);

  if (status === 'buffered') {
    const buffered = firstValue(record, ['buffered']);
    const total = firstValue(record, ['total']);
    const missingFields = [];
    if (!openId) missingFields.push('open_id');
    if (buffered === undefined) missingFields.push('buffered');
    if (total === undefined) missingFields.push('total');
    if (missingFields.length) return missing(missingFields);
    text = `📎 收到 ${buffered} 个文件（共 ${total} 个待提交）。全部上传完成后发送「提交」或 submit 触发报销流程。`;
  } else if (status === 'no_attachments') {
    if (!openId) return missing(['open_id']);
    text = '没有发票，请先上传发票图片，再发送 submit 或 提交。';
  } else if (status === 'not_cn_roster') {
    if (!openId) return missing(['open_id']);
    text = '此工作流仅服务 CN 团队。如有疑问联系管理员。';
  } else if (status === 'submitter_received') {
    const submissionId = textValue(record, ['submission_id', 'submissionId']);
    const missingFields = [];
    if (!openId) missingFields.push('open_id');
    if (!submissionId) missingFields.push('submission_id');
    if (missingFields.length) return missing(missingFields);
    text = `✅ 报销已收到，财务审核中。\nID: ${submissionId}`;
  } else if (status === 'cancel') {
    if (!operatorOpenId) return missing(['operator_open_id']);
    receiveId = operatorOpenId;
    text = '已取消本次报销。';
  } else if (status === 'invalid_split') {
    const errors = Array.isArray(record.errors) ? record.errors : [];
    const missingFields = [];
    if (!operatorOpenId) missingFields.push('operator_open_id');
    if (!errors.length) missingFields.push('errors');
    if (missingFields.length) return missing(missingFields);
    receiveId = operatorOpenId;
    text = `核对失败：\n- ${errors.join('\n- ')}\n\n请修改后再次点击 确认提交。`;
  } else if (status === 'clear') {
    if (!openId) return missing(['open_id']);
    text = '已清空缓存。请重新上传发票，然后发送「提交」。';
  } else if (status === 'cooldown') {
    if (!openId) return missing(['open_id']);
    text = '上一笔报销刚提交，正在处理中。同一个用户 1 分钟内不能重复提交，请稍等。';
  } else {
    return { skip: true, reason: 'unsupported status' };
  }

  return {
    message_type: 'lark_text_message',
    status,
    lark: {
      path: MESSAGE_PATH,
      body: textMessage(receiveId, text)
    }
  };
}

function totalsText(totals, separator, amountFirst) {
  const entries = Object.entries(totals || {});
  if (!entries.length) return '';
  return entries.map(([currency, amount]) => {
    const fixed = Number(numberValue(amount)).toFixed(2);
    return amountFirst ? `${fixed} ${currency}` : `${currency} ${fixed}`;
  }).join(separator);
}

function buildReviewPackage(input) {
  const record = source(input || {});
  const submissionId = textValue(record, ['submission_id', 'submissionId']);
  const openId = textValue(record, ['open_id', 'openId']);
  const missingFields = [];
  if (!submissionId) missingFields.push('submission_id');
  if (!openId) missingFields.push('open_id');
  if (missingFields.length) return missing(missingFields);

  const receipts = Array.isArray(record.receipts) ? record.receipts : [];
  const attachments = Array.isArray(record.receipts) ? record.receipts : (Array.isArray(record.attachments) ? record.attachments : []);
  const totals = record.totals && typeof record.totals === 'object' ? record.totals : {};
  const payeeName = textValue(record, ['payee_name', 'payeeName'], '?') || '?';
  const totalSummary = totalsText(totals, ' | ', false) || '?';
  const formUrl = FORM_BASE_URL + submissionId;
  const reviewerText = `📋 CN报销待审核 — ${payeeName}\n发票: ${receipts.length} 张\n原币合计: ${totalSummary}\n\n📝 审核链接:\n${formUrl}`;

  const forwardMessages = attachments.filter(a => a && a.message_id).map(a => ({
    path: `/open-apis/im/v1/messages/${a.message_id}/forward?receive_id_type=open_id`,
    body: { receive_id: REVIEWER_OPEN_ID }
  }));

  return {
    message_type: 'cn_reimbursement_review_package',
    submission_id: submissionId,
    form_url: formUrl,
    reviewer_open_id: REVIEWER_OPEN_ID,
    lark: {
      reviewerMessage: {
        path: MESSAGE_PATH,
        body: textMessage(REVIEWER_OPEN_ID, reviewerText)
      },
      forwardMessages,
      submitterAck: {
        path: MESSAGE_PATH,
        body: textMessage(openId, `✅ 报销已收到，财务审核中。\nID: ${submissionId}`)
      }
    }
  };
}

function normalizeIsoDate(value) {
  if (value === undefined || value === null) return '';
  const match = String(value).trim().match(/^(\d{4}-\d{2}-\d{2})/);
  return match ? match[1] : '';
}

function firstReceiptDate(receipts) {
  for (const receipt of receipts || []) {
    const date = normalizeIsoDate(receipt && receipt.date);
    if (date) return date;
  }
  return '';
}

function rowsFromSplits(splits, total) {
  const errors = [];
  const rows = [];
  const totalNumber = numberValue(total);
  for (const key of Object.keys(splits || {})) {
    if (!VALID_SUBBRANDS.includes(key)) {
      errors.push(`Unknown subbrand in splits: ${key}`);
      continue;
    }
    const cny = Number(numberValue(splits[key]));
    if (!Number.isFinite(cny)) {
      errors.push(`Non-numeric split value for subbrand: ${key}`);
      continue;
    }
    if (cny > 0) {
      const rounded = Number(cny.toFixed(2));
      rows.push({
        subbrand: key,
        cny: rounded,
        percentage: totalNumber > 0 ? Number(((rounded / totalNumber) * 100).toFixed(2)) : 0,
        dept_head_user_ids: [key === 'AetherLink' ? JASON_USER_ID : ADA_USER_ID]
      });
    }
  }
  if (!rows.length && !errors.length) errors.push('No non-zero splits found');
  return { rows, errors };
}

function normalizeRows(record) {
  if (Array.isArray(record.rows) && record.rows.length) {
    return {
      rows: record.rows.map(r => ({
        subbrand: r.subbrand,
        cny: Number(numberValue(r.cny).toFixed(2)),
        dept_head_user_ids: Array.isArray(r.dept_head_user_ids) ? r.dept_head_user_ids : (Array.isArray(r.deptHeadUserIds) ? r.deptHeadUserIds : [])
      })),
      errors: []
    };
  }

  const splits = firstValue(record, ['splits']);
  const total = firstValue(record, ['actual_cny_total', 'actualCnyTotal', 'cnyTotal']);
  if (!splits || typeof splits !== 'object') return { rows: [], errors: [], missing: ['splits'] };
  if (total === undefined) return { rows: [], errors: [], missing: ['actual_cny_total'] };
  return rowsFromSplits(splits, total);
}

function buildApprovalInstance(input) {
  const record = source(input || {});
  const userId = textValue(record, ['user_id', 'userId']);
  const bankCard = textValue(record, ['bank_card', 'bankCard']);
  const receipts = Array.isArray(record.receipts) ? record.receipts : [];
  const approvalUploads = Array.isArray(record.approval_uploads)
    ? record.approval_uploads
    : (Array.isArray(record.approvalUploads) ? record.approvalUploads : []);
  const date = firstReceiptDate(receipts) || normalizeIsoDate(firstValue(record, ['approvalDate', 'fallbackDate', 'isoDate']));

  const missingFields = [];
  if (!userId) missingFields.push('user_id');
  if (!bankCard) missingFields.push('bank_card');
  if (!date) missingFields.push('approvalDate');

  const rowResult = normalizeRows(record);
  if (rowResult.missing) missingFields.push(...rowResult.missing);
  if (missingFields.length) return missing([...new Set(missingFields)]);
  if (rowResult.errors.length) return { invalid: true, errors: rowResult.errors };

  const categoryLabel = textValue(record, ['category_label', 'categoryLabel', 'category']);
  const categoryCode = textValue(record, ['category_code', 'categoryCode']) || CATEGORY_MAP[categoryLabel] || CATEGORY_MAP['技术服务费'];
  const defaultSubbrand = textValue(record, ['default_subbrand', 'defaultSubbrand'], 'CN') || 'CN';
  const purposeText = textValue(record, ['purpose']) || `${defaultSubbrand} 报销`;
  const formUrl = textValue(record, ['reimbursement_form_url', 'reimbursementFormUrl']);
  const remarksValue = formUrl ? `${DISCLAIMER}\n\n报销明细表: ${formUrl}` : DISCLAIMER;
  const fileTokens = approvalUploads.filter(u => u && u.code).map(u => u.code);

  const rows = rowResult.rows.map(r => [
    { id: WIDGETS.row_department, type: 'input', value: r.subbrand },
    { id: WIDGETS.row_dept_head, type: 'contact', value: r.dept_head_user_ids },
    { id: WIDGETS.row_date, type: 'date', value: `${date}T00:00:00Z` },
    { id: WIDGETS.row_category, type: 'radioV2', value: categoryCode },
    { id: WIDGETS.row_purpose, type: 'textarea', value: purposeText },
    { id: WIDGETS.row_currency, type: 'radioV2', value: CNY_OPTION },
    { id: WIDGETS.row_amount, type: 'amount', value: r.cny, currency: 'CNY' },
    { id: WIDGETS.row_bank_card, type: 'input', value: bankCard }
  ]);

  const form = [
    { id: WIDGETS.field_list, type: 'fieldList', value: rows },
    { id: WIDGETS.attachment_top, type: 'attachmentV2', value: fileTokens },
    { id: WIDGETS.remarks, type: 'input', value: remarksValue }
  ];

  const approvalBody = {
    approval_code: APPROVAL_CODE,
    user_id: userId,
    form: JSON.stringify(form)
  };

  return {
    message_type: 'lark_approval_instance',
    open_id: textValue(record, ['open_id', 'openId']),
    submission_id: textValue(record, ['submission_id', 'submissionId']),
    form,
    approval_body: approvalBody,
    lark: {
      path: APPROVAL_PATH,
      body: approvalBody
    }
  };
}

function buildSubmitterLinkMessage(input) {
  const record = source(input || {});
  const receiveId = textValue(record, ['receive_id', 'receiveId', 'open_id', 'openId']);
  const instanceCode = textValue(record, ['instance_code', 'instanceCode']);
  const missingFields = [];
  if (!receiveId) missingFields.push('open_id');
  if (!instanceCode) missingFields.push('instance_code');
  if (missingFields.length) return missing(missingFields);

  const serialNumber = textValue(record, ['serial_number', 'serialNumber'], instanceCode) || instanceCode;
  const receipts = Array.isArray(record.receipts) ? record.receipts : [];
  const validReceipts = receipts.filter(r => !r.duplicate);
  const totalStr = totalsText(record.totals || {}, '、', true) || 'N/A';
  const receiptLines = validReceipts.map((r, i) => {
    const merchant = r.merchant || '未知商家';
    const date = r.date ? ` · ${r.date}` : '';
    return `${i + 1}. ${merchant}${date} · ${r.original_currency || ''} ${Number(numberValue(r.original_amount)).toFixed(2)}`;
  }).join('\n');
  const count = validReceipts.length;
  const text = `✅ 报销已提交审批！\n\n发票：${count} 张\n金额：${totalStr}\nLark No：${serialNumber}${receiptLines ? `\n\n发票明细：\n${receiptLines}` : ''}`;

  return {
    message_type: 'lark_text_message',
    instance_code: instanceCode,
    serial_number: serialNumber,
    lark: {
      path: MESSAGE_PATH,
      body: textMessage(receiveId, text)
    }
  };
}

function buildPayload(input) {
  const root = input || {};
  const record = source(root);
  const mode = root.mode || record.mode || 'build_approval_instance';
  if (mode === 'parse_event') return parseEvent(root);
  if (mode === 'build_status_message') return buildStatusMessage(root);
  if (mode === 'build_review_package') return buildReviewPackage(root);
  if (mode === 'build_approval_instance') return buildApprovalInstance(root);
  if (mode === 'build_submitter_link_message') return buildSubmitterLinkMessage(root);
  return { skip: true, reason: 'unsupported mode' };
}

if (require.main === module) {
  process.stdout.write(`${JSON.stringify(buildPayload(readInput()), null, 2)}\n`);
}

module.exports = { buildPayload };
